# syntax=docker/dockerfile:1

FROM public.ecr.aws/lambda/python:3.7
RUN python3 -m pip install --upgrade pip && \
python3 -m pip install --upgrade setuptools && \
yum install -y gcc python37-devel

COPY requirements.txt ./
COPY queue_consumer.py ./
RUN pip3 install -r requirements.txt
CMD ["queue_consumer.lambda_handler"]